params {
    config_profile_name        = 'EMBL_HD'
    config_profile_description = 'EMBL Heidelberg cluster profile'
    config_profile_url         = 'https://git.embl.de/data-sciences/sci-workflows/nextflow-config'
}

apptainer {
    enabled        = true
    autoMounts     = true
    docker.enabled = false

    // We use -H to point to a folder named 'fake_home' 
    // Apptainer will create this folder if it doesn't exist
    runOptions = '-C -H $PWD -B /g:/g -B /scratch/${USER}:/scratch/${USER}'

    cacheDir       = "/g/mif-hd/shared/cache_apptainer/" //or can use scratch
    pullTimeout    = "3 hours"
    envWhitelist   = 'CUDA_VISIBLE_DEVICES'
}


executor {
    name            = "slurm"
    queue           = 'htc-el8'
    scratch         = true
    queueSize       = 200
    submitRateLimit = "10/1sec"
    pollInterval    = "10sec"
    exitReadTimeout = "5 min"
}


process {
    cache         = 'lenient'
    maxRetries    = 3
    afterScript   = 'sleep 10'
    beforeScript  =
        """
        if [ -n "\$CONDA_PREFIX" ]; then
            export PATH="\$CONDA_PREFIX/bin:\$PATH"
            export LD_LIBRARY_PATH="\$CONDA_PREFIX/lib:\$LD_LIBRARY_PATH"
        fi
        """
    queue         = { (task.time <= 14.d && task.memory < 256.GB && (task.memory.div(task.cpus)) <= 4.GB) ? "htc-el8" : "bigmem" }

    withLabel: 'gpu' {
        queue            = 'gpu-el8'
        containerOptions = '--nv' // Enable NVIDIA support
        clusterOptions   = '--gres=gpu:1 -C "gpu=L40s|gpu=3090"'
    }

    withLabel: 'bigmem' {
        queue = 'bigmem'
    }

    withLabel:low_qos {
        clusterOptions = '--qos=low'
    }
}


