name: "ometiff_to_zarr"
description: Converts OME-TIFF images to OME-ZARR format using the pymif library, including automated chunking and pyramid generation.
keywords:
  - imaging
  - ometiff
  - zarr
  - pyramid
  - microscopy
tools:
  - "pymif":
      description: "Python Microscope File manager for high-content screening data."
      homepage: "https://github.com/grinic/pymif"
      documentation: "https://github.com/grinic/pymif"
      tool_dev_url: "https://github.com/grinic/pymif"
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information.
        e.g. `[ id:'sample1', exp_name:'Exp01', well:'A1', field:'1', num_layers:3, chunk_size:'1 1 8 256 256' ]`
  - tiff:
      type: file
      description: The input OME-TIFF file.
      pattern: "*.{tif,tiff,ome.tif,ome.tiff}"

output:
  - zarr:
      type: directory
      description: The output OME-ZARR store.
      pattern: "*.zarr"
  - versions:
      type: file
      description: File containing software versions.
      pattern: "versions.yml"

authors:
  - "@grinic"
  - "@nvivanco"
