name: pymif-cp
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - git
  - pyqt6
  - qtpy
  - superqt
  - pyqtgraph
  - qtconsole
  - pip:
      - -r pymif-cellpose-env-clean.txt
